### ISSUE TITLE
Can't properly use mod

### ISSUE THREAD

**Issue by Smoldar-og** [kamcknig/pick-up-stix#100]
After updating to Foundry 0.6.6 and DnD5e 0.96 is no longer possible to drag items to canvas or create new instances. Tested with only this mod and attempting to place item on canvas no longer display the container window. Interacting with already existing chests is possible.

If the currency writing field is left blank the field is removed 

**To Reproduce**
Drag item from the pack into the canvas
There is no window prompt to make into container or item

Interacting with already existing container don't remove the gold from it

Deleting the currency writing field and leaving it blank makes it impossible to further interact with the fields

**Expected behavior**
Drooping the item on canvas should show a window to make the item either container or item

Gold should be removed from chest

**Screenshots**
https://i.imgur.com/D3xfYPU.png

https://youtu.be/avVn2LGrudc

Can't add proof/evidence from the gold not being removed due to only having one chest active and that chest being the one with unusable currency (was populating additional loot into dungeon)

**Foundry Version**
0.6.6 (DnD5e 0.9.6)

**Pick-Up-Stix Version**
0.8.2

**Comment by kamcknig** [comment]
@Smoldar-og Hi! There was a bug in my version check code that broke for users using 0.6.6 of Foundry, the latest update should have a fix for that. It was fixed in version 0.8.7
