### ISSUE TITLE
It's not working on Simple World-Building

### ISSUE THREAD

**Issue by brunocalado** [kamcknig/pick-up-stix#101]
Hi.

It's not working on Simple World-Building. I can't drop items from the PC inventory to the map. I can't drop from Items to map too.

![image](https://user-images.githubusercontent.com/4999783/91603866-1e159400-e944-11ea-864d-d3648e96712c.png)

**Comment by kamcknig** [comment]
@brunocalado , I just installed the system and created a world from scratch and it seemed to be working for me. Have you tried disabling all other add-ons to be sure it's not an incompatibility? If it is, I'll gladly look into it if we can determine what other add-on it is.
