### ISSUE TITLE
New Version Broke Things

### ISSUE THREAD

**Issue by Nuku** [kamcknig/pick-up-stix#104]
Simply, once Foundry updated, I lost the ability to put items down at all.

**Comment by kamcknig** [comment]
@Nuku Which version of Foundry and which version of Pick-Up-Stix are you using? No other users have reported this and I've used it today and it seems OK. If you can reproduce it and help me to do so, I'll gladly look at it!

**Comment by kamcknig** [comment]
If you updated from Foundry 0.6.5 to 0.6.6 there was a bug that was fixed in version 0.8.7 of Pick-Up-Stix to make it work with Foundry 0.6.6.

**Comment by Grygon** [comment]
Also having trouble.
Stix version 0.10.2
Foundry version 0.6.6
5e version 0.96

Tried uninstalling/reinstalling stix but no luck.

Getting these errors that I'm guessing are related:
![image](https://user-images.githubusercontent.com/647846/92281014-54ad5a80-eec0-11ea-8450-71ebbac645e7.png)

**Comment by kamcknig** [comment]
Please uninstall and reinstall the module. Somewhere around version 0.8.x it stopped finding the update. the current latest version should be 0.10.2
