### ISSUE TITLE
Properties Reset On Drop/Pickup

### ISSUE THREAD

**Issue by yoshikidneo** [kamcknig/pick-up-stix#106]
So I have a hand crossbow the players can drop and use as a turret of sorts. The issue is that when they pick it back up, the properties of ammunition, charges, etc reset to blank. I've noticed that most items that use charges get wiped as well when they are dropped, even though the items sheet that I created has the information filled out.

**Comment by kamcknig** [comment]
This makes sense with how it's been developed. I'm not keep tracking of updated values. I am doing a refactor right now that I hope might help solve this issue.

**Comment by kamcknig** [comment]
@yoshikidneo Could you please test this in 0.11.0? I have changed  the way data is stored, and it could solve the issue with things like this

**Comment by kamcknig** [comment]
Closing this issue, please reopen if need be. you might have to uninstall/reinstall the module as the updating isn't working sometimes it seems
