### ISSUE TITLE
Unable to use with vtta-beyond-iconizer

### ISSUE THREAD

**Issue by kunxin-chor** [kamcknig/pick-up-stix#107]
**Describe the bug**

**To Reproduce**
1. Install the vtta-beyond-iconizer
2. In module settings, go to configure settings, for Iconizer, set the following settings
3. Set icon replacement policy to `Replace all Icons`
4. Set base dictionary to `World of Warcraft Icons (online, wowhead.com)`
5. Save the settings
6. After reload, drag an item with the replaced icon onto the map
7. Select `item` from the pop-up

**Expected behavior**
Item appears on the map

**Actual outcome**
1. No item appears. Console will reveal CORS error
2. Reloading the map will cause progress to stop due to CORS error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14900791/92697062-5cb44100-f37d-11ea-9ac9-83d2c8736bac.png)

**Foundry Version**
0.66

**Pick-Up-Stix Version**
0.10.2

**Comment by kamcknig** [comment]
I'm not sure how mine could cause a CORs issue. Are you sure this isn't the Chrome issue that Atropos is looking into solving https://gitlab.com/foundrynet/foundryvtt/-/issues/2982. Did you try firefox?
