### ISSUE TITLE
Doesn't work in wfrp4e

### ISSUE THREAD

**Issue by Zan135kin200** [kamcknig/pick-up-stix#108]
When I try to has a CC test with a weapon (from macro toolbar or directly from character sheet by clicking the weapon) it throw me an error : "Maximum depth exceeded"
at foundry.js:3389 and 3386.
Foundry is 0.6.6 version
Wfrp4e is 2.1.0
Pick Up Stix is 0.10.2
On Foundry Discord someone told me pick up stix mod is responsible of that because it modify items somewhere, even if I deactivate or deinstall the module.
Regards

**Comment by kamcknig** [comment]
Hello, I'm not sure I understand the issue.

Can you list steps to create any actors/items that are having the issue, and how to reproduce this?

**Comment by Zan135kin200** [comment]
Hello, to reproduce :
Create a world with warhammer 4ed v2.1.0 system
Install Pick up stix
Create a character
Create a weapon or use existing one
Drag and drop the weapon to the character
Drag and drop the equipped weapon to the macrobar
Click on the created icon on the macrobar
Bug

To solve my issue I had to deinstall entirely the module and create another
new world, because even if I deactivate the mod it continue bugging. After
that I had to migrate all my datas on the new world. (So I don't want to
reproduce the bug on the new one ;-) )
I hope this will help you to understand the issue.

Have a good day


Le lun. 14 sept. 2020 à 21:09, Kyle McKnight <notifications@github.com> a
écrit :

**Comment by kamcknig** [comment]
@Zan135kin200 Hi, could you please re-test this with version 0.11.0? I just did a test using those steps and it seems to have worked. I made a pretty large refactor to the data structure and it seems to have solved quite a few compatibility issues.

**Comment by Zan135kin200** [comment]
Hey it seem's to work now! Great and many thanks!

**Comment by kamcknig** [comment]
Excellent! Glad to hear
