### ISSUE TITLE
SWADE: Items in inventory before pick-up-stix was activated disappear upon dragging them co the map/another token.

### ISSUE THREAD

**Issue by SalieriC** [kamcknig/pick-up-stix#109]
**Describe the bug**
Activating Pick-Up-Stix in an existing SWADE world can lead to loss of items: Items that were present before the module was activated will disappear when trying to drop or trade them. The following error messages appear:
![image](https://user-images.githubusercontent.com/1230041/92809438-e6cfca00-f3bc-11ea-87be-8c6923791994.png)
![image](https://user-images.githubusercontent.com/1230041/92809381-db7c9e80-f3bc-11ea-8782-8f88e3d115e3.png)

This is a serious issue and sadly makes the module unusable for me.

**To Reproduce**
Create a world with the SWADE system. Create some actors and items (doesn't matter whether from the actor sheet directly or the sidebar). Activate Pick-Up-Stix. Drag the items to the map/another actor.

**Foundry/SWADE Version**
0.6.6/0.11.3

**Pick-Up-Stix Version**
0.10.2

**Comment by kamcknig** [comment]
I am working on a refactor of the data right now. I'll have to look into if this is an issue after my refactor. As of now I don't plan on fixing it for version 0.10.2. 

I'll have a fix or at least an updated/explanation on this when I release my next 0.11.x version.

**Comment by kamcknig** [comment]
@SalieriC Could you please test this in version 0.11.0 of Pick-Up-Stix. I just did a test run on a new world with SWADE and it worked. I don't know much about SWADE though or any testing scenarios I should run through

**Comment by SalieriC** [comment]
@kamcknig sure, if you tell me how to install it. It's not yet found by the updater.

**Comment by kamcknig** [comment]
Unfortunately it seems to be an issue with my module and foundry that foundry doesn't find the update, I have an open question on the discord about it. If you uninstall and reinstall it should work

**Comment by SalieriC** [comment]
My small test suggested that it is now working just fine. Thank you very much. I will get back to you should the issue arises during play but for now the issues I encountered the last time seem fixed. =)

**Comment by kamcknig** [comment]
Glad to hear it!
