### ISSUE TITLE
feature request - Lock inventory inside of containers on pick up

### ISSUE THREAD

**Issue by Ikxale** [kamcknig/pick-up-stix#110]
When picking up a container (in my case, the backpack from pathfinder second edition) the contents get automatically sorted into other categories, such as gold getting moved to treasure tab, weapons to weapon tab.

this tends to be somewhat troublesome, as in PF2e certain containers reduce the weight of things inside them, most notably backpacks. this is a very niche thing, but i feel it would improve the quality of the module

also i don't know how to mark this as a feature request i literally have never used github before

**Comment by kamcknig** [comment]
I'm not familiar with pathfinder enough, and I mostly develop with D&D in mind. Could you please list out your foundry version, pathfinder version, and my module version along with the steps that I can follow to reproduce the issue?

Thanks

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
