### ISSUE TITLE
Working with Foriens Unidentified Items module

### ISSUE THREAD

**Issue by darthrader** [kamcknig/pick-up-stix#111]
**Describe the bug**
It appears that pick-up-stix is not working well with Forien's unidentified items.  See screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/11488238/92948694-c38e3480-f427-11ea-8aa3-47720e9b0029.png)

**Comment by kamcknig** [comment]
@darthrader Could you please test this in version 0.11.0? I don't really know how to use the unidentified items module, but i was able to mystify and add the item to a container and it showed as unidentified, but I don't really know the process afterward of what I need to test

**Comment by powerkor** [comment]
> @darthrader Could you please test this in version 0.11.0? I don't really know how to use the unidentified items module, but i was able to mystify and add the item to a container and it showed as unidentified, but I don't really know the process afterward of what I need to test

In the title bar it should say identify but it says mystify. If you open the mystified item before putting it in the container you’ll see the difference

**Comment by kamcknig** [comment]
@powerkor Ah! I didn't see the title bar options. So in a test I just did with 0.11.0 it seemed to work then.

**Comment by powerkor** [comment]
While I’m here can you tell me once someone opens the container how they pickup the item? I can’t seem to figure it out

**Comment by kamcknig** [comment]
There should be a hand icon on the right side

![2020-09-20 16_05_46-Window](https://user-images.githubusercontent.com/705490/93721014-3b144000-fb5b-11ea-9d4d-2c98fc5bed11.png)

**Comment by kamcknig** [comment]
Closing this issue, please reopen if need be
