### ISSUE TITLE
Getting locked out of Character screen if picking up resized object

### ISSUE THREAD

**Issue by RedSoarer** [kamcknig/pick-up-stix#113]
I was trying to place some items, short swords and arrows on the ground for players to pick up. Not wanting to have the items take the entire square I resized them to 0.3. After picking up with test character I noticed I could no longer open the character sheet, neither form double clicking the token nor from the bar on the right. I had to delete the character entirely (token on map and form side bar) and reimport.

This is being done in Pathfinder 2nd Edition v1.10.10.1973 game world

**To Reproduce**
1. Place item on map
2. Double click item, or right click + left click cog to access options
3. Slide resize to 0.3 (not tested with other sizes)
4. Exit item window and pick item up with character
5. Attempt to open character sheet

**Expected behavior**
Character sheet should open

**Screenshots**

**Foundry Version**
0.6.6

**Pick-Up-Stix Version**
0.10.2

**Comment by kamcknig** [comment]
@RedSoarer Could you please retest this in version 0.11.0 of Pick-Up-Stix? I just tested with a new Pathfinder world and yoru scenarios seemed to work for me there

**Comment by RedSoarer** [comment]
@kamcknig Tested it with 0.11.0 and it worked as expected. The smaller item did not lock me out of the sheet. Odd thing was I tried to update though the FoundryVTT interface and it kept me at version 0.10.2. I then checked the modules list and saw that the latest was indeed 0.11.0. 

Uninstalled the 0.10.2 version that wasn't updating and reinstalled the 0.11.0 to test and worked just fine.

**Comment by kamcknig** [comment]
Unfortunately that's been an ongoing issue with my module. I raised a question on one of the discord channels to try to find out why

**Comment by RedSoarer** [comment]
Thanks for the really quick replies and glad that it was such a simple fix. Awesome module by the way. I hope the update issue can get squared away just as quickly.
