### ISSUE TITLE
Container image on map does not update

### ISSUE THREAD

**Issue by Pawper** [kamcknig/pick-up-stix#114]
**Describe the bug**
The image for the container that is on the map does not update to match what I have set.

**To Reproduce**
see screenshots below

**Expected behavior**
The image on the map updates.

**Screenshots**
Defaults set to be different:
![image](https://user-images.githubusercontent.com/22269691/94076040-216c3600-fdb1-11ea-893b-a53c3b86322b.png)

Also tried in the settings for the container itself:
![image](https://user-images.githubusercontent.com/22269691/94076122-495b9980-fdb1-11ea-8db8-26016f882bd9.png)

It still has the old image:
![image](https://user-images.githubusercontent.com/22269691/94076244-7f008280-fdb1-11ea-87d0-6b779e62c323.png)

**Foundry Version**
0.6.6

**Pick-Up-Stix Version**
0.11.3

**Comment by kamcknig** [comment]
@Pawper I just want to be sure after changing the image, you have to click close for the update. Now I don't seem to be getting the issue you are having, but I did notice that when I change the image and the token updates, it actually shows the 'open' image even when it's closed after the update. so there is indeed a bug here. Can you please try to change th eopen image and see if it updates?

**Comment by kamcknig** [comment]
Should be fixed in release 0.11.7. You might need to manually update as there were issues for awhile with automatic updates of my module

**Comment by powerkor** [comment]
Also for clarity I mean the screen where the item is doesn’t show when you click on the chest. Nothing happens at all... but I’ll try the update

**Comment by kamcknig** [comment]
@powerkor OK! If this version doesn't fix it, then I'll re-open this issue. Thanks.
