### ISSUE TITLE
Feature Request - Add item button

### ISSUE THREAD

**Issue by Pawper** [kamcknig/pick-up-stix#116]
Hello,

Please add something like the +Add button from Loot Sheet 5e, so that we can add items directly in the UI without dragging in.
![image](https://user-images.githubusercontent.com/22269691/94084272-018d4000-fdba-11ea-9194-0a6a5bdb7ee4.png)

**Comment by kamcknig** [comment]
@Pawper I actually had this at first but the way the data structure I had set up broke things. I believe I can actually easily add this in for the 0.11.x releases as I refactored that data structure. Will put it on the backlog

**Comment by kamcknig** [comment]
Closing this as I've added it to my trello board
