### ISSUE TITLE
Feature Request - Edit item button

### ISSUE THREAD

**Issue by Pawper** [kamcknig/pick-up-stix#117]
Hello,

Please add something like the edit from Loot Sheet 5e.

![image](https://user-images.githubusercontent.com/22269691/94095249-30191400-fdd6-11ea-94e5-7b2da4f9c84b.png)

**Comment by kamcknig** [comment]
@Pawper same as the add item button :) will add it to the backlog, this should now be doable with the new data structure i have for the 0.11.x releases

**Comment by kamcknig** [comment]
Closing this as I've added it to my trello board
