### ISSUE TITLE
Feature Request - Loot All button

### ISSUE THREAD

**Issue by Pawper** [kamcknig/pick-up-stix#118]
Hello,

Please add something like the Loot All button from Loot Sheet 5e.

![image](https://user-images.githubusercontent.com/22269691/94095357-6eaece80-fdd6-11ea-8f07-92ae55ac532d.png)

**Comment by kamcknig** [comment]
@Pawper Added to the backlog, should be fairly simple

**Comment by kamcknig** [comment]
Closing this as I've added it to my trello board
