### ISSUE TITLE
Feature Request - Item costs for items

### ISSUE THREAD

**Issue by Pawper** [kamcknig/pick-up-stix#119]
It would be cool if items could have items as a requirement. So I could have a cauldron filled with a potion, but PCs would need glass bottles. Ideally it automatically grabs them from the player's inventory and has a confirmation popup, but if they have to drag the glass bottles in, that works.

**Comment by kamcknig** [comment]
@Pawper Fun idea, I'll have to think about implementation but will add to the backlog. this might be down the road a little bit as there are some other features I want to add first.

**Comment by kamcknig** [comment]
Closing since it's on my trello
