### ISSUE TITLE
Simple World Building - drop item from inventory

### ISSUE THREAD

**Issue by aeciobf** [kamcknig/pick-up-stix#120]
In the Simple World Building, dropping the item from inventory create it in the map, but the item continues in the inventory.

**Comment by kamcknig** [comment]
@aeciobf Confirmed as well, D&D5e seems to not have the problem, so it's specific to this system. I'll take a look, thanks for the report

**Comment by kamcknig** [comment]
I'm not sure if this is the issue or not but I noticed some differences between Simple World building and other systems. I created an issue for simple world building in case the isssue lies with them. If it does not when they get back to me,j i'll look further. For reference, the issue I opened https://gitlab.com/foundrynet/worldbuilding/-/issues/21

**Comment by kamcknig** [comment]
@aeciobf I'm working on a refactor due to a DB bloat issue that was found. I have tested this in that refactor and it appears to be working for Simple World building. So please try again when the 0.12.x line is released.

**Comment by aeciobf** [comment]
I tested the new version in Foundry 0.75 and works well!
Thanks!
