### ISSUE TITLE
Feature Request: Changing Token Size

### ISSUE THREAD

**Issue by Hydrall** [kamcknig/pick-up-stix#121]
I have some tokens I'd like to use, but some of them are larger than 1x1 - as it stands I can't quite use them without the token being oddly shrunk. (Assuming I'm not just missing how to do this with a container token.)

**Comment by kamcknig** [comment]
Hi, @Hydrall! Could you please provide your setup? Maybe the image you're using and steps? The scaling I added was pretty simple and wasn't well thought out, I just put it in on a whim.
