### ISSUE TITLE
Sandbox System - Items taken do not go into inventory

### ISSUE THREAD

**Issue by rholman-PRFT** [kamcknig/pick-up-stix#156]
**Describe the bug**
I know that this is optimized for DND5e, just wanted to let you know, using the sanbox system, one can "take" items from a container, but they are not added to the taker's character sheet.

**To Reproduce**
1. Click a container
2. Loot it
3. Look at character sheet, observe no items are added.

**Expected behavior**
Items should be added as type "cItem" to character sheet.

**Foundry Version**
0.6.6

**Pick-Up-Stix Version**
0.12.4

**Comment by kamcknig** [comment]
Hmm this should work on most ssystems, so there might be a bug, I'll attempt to reproduce at some point this week.

**Comment by kamcknig** [comment]
I can't even give a player items in this system. I create a new item as normal, and then drag it to a character sheet, I don't get the item.
