### ISSUE TITLE
Feature Request - When token is marked as defeated convert to a Item Container for make "lootable" to the party

### ISSUE THREAD

**Issue by p4535992** [kamcknig/pick-up-stix#158]
**Describe the feature**

With a new settings to the module (so everyone  can choose to enable or disable) when a token (usually NPC) is marked as "Defeated", convert (or replace not sure about the code) to a Item container, with the same image of the "Defeated" token and with the currency and the items .

[OPTIONAL] Manage a miss click when remove the condition "Defeated" re-pristine the previous state of the NPC.

[OPTIONAL] The same idea can be used when a player say "I want to steal to the npc"  and i marked with some specific condition that NPC (for example sleep) and show to the player the items on the npc.

Priority : Low 

P.S. I really like this module there is some way i can support the development ?

**To Reproduce**

1. Select a token
2. Mark wiht the condition "Defeated"
3. The token "become" a Loot Container lottable from the party, with same currency and items of the previous npc

**Foundry Version**

Foundry VTT Version: 0.7.5
Operating System: \[Linux\]
How Are You Using Foundry: \[Linux,Native Application (Electron), Chrome\]
Which Game System: Dungeons and Dragons 5th Edition, version 0.98
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Pick-Up-Stix Version**

0.12.4

**Comment by kamcknig** [comment]
Hi! I actually have this in my backlog of features :-D There are quite a few of them there, though I appreciate the fleshed out ideas as I'm sure I won't think of things like that hah!

I am definitely open to PRs, I've got another rewrite in mind that I think can alleviate the speed issues and probably make it a lot cleaner as well, but I've also got a huge backlog of features to implement as well

**Comment by p4535992** [comment]
No problem,  you want i close this ticket?
