### ISSUE TITLE
Double clicking breaks the Container 

### ISSUE THREAD

**Issue by DestralC** [kamcknig/pick-up-stix#159]
**Describe the bug**
Double-clicking on a container opens two container sheets that when closed still prevent the re-opening of the container. Listing that "Another Character is interacting with this item. Please wait your turn or ask them to close their loot sheet" Even while no sheet is open.

This doesn't seem to occur with a Dm roll. Found while testing, logged in a second time with an incognito tab.
This also seems to duplicate the container Item in the Item Directory

**To Reproduce**
1. Create a container Item and Drop  it on the map'
2. Log in to a player account
3. double click the container on the map
4. Close both item containers that open

**Expected behavior**
Double Clicking should only open a single sheet, or closing both pages should allow for interaction

**Foundry Version**
0.7.6

**Pick-Up-Stix Version**
0.12.4

**Comment by kamcknig** [comment]
Hi, there is now a new version out 0.13.3, if you could try that one. Though you will have to recreate any items/containers as 0.13.x is not compatible with 0.12.x

**Comment by kamcknig** [comment]
@DestralC Hi, just wanted to see if this was still happening for you if you've tried the latest version?

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
