### ISSUE TITLE
Console filled up with pick up stix logs

### ISSUE THREAD

**Issue by amcvfx** [kamcknig/pick-up-stix#161]
**Describe the bug**
Pick-up-stix is sending constant logs to the console which I'm assuming is going to slow things down. It clogs up the console very quickly.

**Screenshots**
![image](https://user-images.githubusercontent.com/35099081/99426452-007d1880-28fc-11eb-9c86-56a5816c3e40.png)

**Foundry Version**
0.77

**Pick-Up-Stix Version**
0.13.3

**Comment by kamcknig** [comment]
I'll add a debug flag for these, thanks!

**Comment by kamcknig** [comment]
Hello, @amcvfx v0.13.6 now has a CONFIG.debug.pickUpStix flag that is false by default so log messages will not show aside from console.error messages
