### ISSUE TITLE
Dropped item does not retain quantity

### ISSUE THREAD

**Issue by Krigsmaskine** [kamcknig/pick-up-stix#163]
**Describe the bug**
Dropping an item with more than 1 in quantity, and then picking up said item resets the quantity to 1.

**To Reproduce**
1. Add a stacking item/quantifiable item such as the torch item to an actor.
2. Edit the item, change the quantity to a number above 1.
3. Drop the item on the ground.
4. Pick up the item, behold the quantity has been set to 1 when picked up. Chatlog shows x1 as well.

**Expected behavior**
The item to retain quantity when dropped/picked up.

**Screenshots**
N/A

**Foundry Version**
0.7.7

**Pick-Up-Stix Version**
0.13.3

**Comment by kamcknig** [comment]
@Krigsmaskine, hello, this is fixed in version 0.13.7. Thank you!
