### ISSUE TITLE
Support unidentified items

### ISSUE THREAD

**Issue by agrtga** [kamcknig/pick-up-stix#164]
Please add support for the unidentified property on items, so that the appropriate description is shown to the players. This applies to the 3.5e SRD system, but possibly also to 5E.

**Comment by kamcknig** [comment]
Hello, do you have more details on this? As far as I knew, the Foundry base system doesn't support unidentified items and the only thing I've seen that allows that is Forien's module for unidentified items. Which in the past I ensured my module was compatible with his.

**Comment by SabbothO** [comment]
Hello, I'm a player of t he 3.5e SRD system as well. I believe unidentified items are built into the 3.5e system. But yes, as it currently is in 3.5e, the item appears with the identified name within a container, and switches back to the unidentified name once in their inventory.

**Comment by Rughalt** [comment]
This will be fixed by my with a PR

**Comment by JamzTheMan** [comment]
For the PF2E system, if Foriens Unidentified (Mystified) item is dragged to the scene or token. it's permanently lost and a "Maximum depth allowed" UI error is displayed.  Is this related?
