### ISSUE TITLE
Looting from container in pf2e system breaks character sheets

### ISSUE THREAD

**Issue by PBobovsky** [kamcknig/pick-up-stix#165]
When using the PF2e system if a player takes an item from a container, their character sheet breaks and can't be opened until it is repaired manually in json.
This doesn't happen if a player picks up the item from the ground directly.

The difference in the character sheet json between the two that I can see is only in the quantity property on the looted object. 
Picking up from container produces: `"quantity": 1,`
Picking up from the ground produces: `"quantity": { "value": 1 },`

**Foundry Version**
0.7.7 (but happened on 0.6.x as well)

**Pick-Up-Stix Version**
0.11.3

**Comment by kamcknig** [comment]
@PBobovsky Hello, can you confirm if this works in the newest version of Pick-Up-Stix? It is now at version 0.13.6. I can't recall where some of the versions broke but at some point auto-updating didn't work. If you try to update and it doesn't work, please uninstall and reinstall pick-up-stix.

**Comment by PBobovsky** [comment]
@kamcknig It works correctly on that version, I did indeed have broken auto-update. Thank you!

**Comment by kamcknig** [comment]
@PBobovsky Glad to hear :)
