### ISSUE TITLE
Looting no longer works on 3.5E SRD

### ISSUE THREAD

**Issue by agrtga** [kamcknig/pick-up-stix#166]
**Describe the bug**
Looting from a container no longer works when using the 3.5E SRD. A wait cursor display shows for a few seconds and then nothing happens. This occurs with currency and other items.

This was working in the last version (although the currency wasn't enabled).

**To Reproduce**
1. Add a container with items
2. Open as player and click button to take item

**Expected behavior**
Item is removed from container and added to character sheet.

**Foundry Version**
0.7.7

**Pick-Up-Stix Version**
0.13.4

**3.5E SRD Version**
0.87.6

**Comment by kamcknig** [comment]
Hello, @agrta, do you have more details on this? I just attempted this with 3.5e SRD 0.87.6 and it seemed to work.

You can also update to the latest 0.13.6 of Pick-up-Stix. Here are my steps:

1. Click create item in item directory
2. Choose container type and give it a name
3. Navigate to folder and open new container config sheet
4. Drag/drop item from item directory onto container sheet to add it to container
5. Drag/drop container to the canvas
6. Control player token and left click container
7. click hand take icon

This worked for me. If it does not work for you, please remove all other modules and try again.

You can also set the CONFIG.debug['pickUpStix'] property in the chrome console to true to show console messages (assuming you update to the latest module version)

**Comment by kamcknig** [comment]
Ahhh, OK, I didn't realize it was part of the 3.5 system, @Rughalt, you might want to take this one for your system
