### ISSUE TITLE
Players unable to see items they have permission to in item directory when Pick-Up-Stix is active

### ISSUE THREAD

**Issue by archeresky** [kamcknig/pick-up-stix#167]
**Describe the bug**
When the module is enabled, my players cannot view any items in the item directory.

**To Reproduce**
The bug is present when the module is active.

**Foundry Version**
0.7.7

**Pick-Up-Stix Version**
0.13.4

**Comment by kamcknig** [comment]
Hello, this should be fixed in the latest version, please try again and let me know, @archeresky
