### ISSUE TITLE
Container stays open after opening the first time regardless of setting (PF2E)

### ISSUE THREAD

**Issue by VeilOfOblivion** [kamcknig/pick-up-stix#169]
**Describe the bug**
A new container appears closed. But as soon as you interact with it, it switches to the open state and stays like that regardless of setting "Can close"

**To Reproduce**
1. Create a new container
2. Configure it to your heart's content but make sure "Can close" is ticked
3. As a player (or GM with a token selected), interact with it
4. See that the token image switches to the open state (which is expected)
5. Close the container (with the close button top left)
6. See that the token image stays in the open state

**Expected behavior**
The icon for the container should switch back to the closed state when the container has set the "Can close" option and the window closes

**Foundry Version**
0.7.7 (PF2E: 1.10.17.2355)

**Pick-Up-Stix Version**
0.13.5

**Details**
No console errors or similar

**Comment by kamcknig** [comment]
This will be fixed in 0.13.8!
