### ISSUE TITLE
Can't drag and drop a new item into a scene from a compendium (PF2E)

### ISSUE THREAD

**Issue by VeilOfOblivion** [kamcknig/pick-up-stix#170]
**Describe the bug**
Dragging and dropping an item from a compendium doesn't create a new item token. Nothing happens visually. A console error is created

**To Reproduce**
1. Open an item compendium (e.g. Equipment)
2. Drag and drop any item on the scene
3. See that no token was created
4. See that there is no dialog asking what you want to create (item or container)
5. See also that there is no item token created in the item tab
6. See a console error "Unexpected token u in JSON at position 0" (details see below)

**Expected behavior**
A new item token is created (at least that is what I expect after watching your video at 0:22)

**Foundry Version**
0.7.7 (PF2E: 1.10.17.2355)

**Pick-Up-Stix Version**
0.13.5

**Details**
Stack Trace:
foundry.js:978 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at duplicate (foundry.js:978)
    at dropItemOnCanvas (main.ts:160)
    at handleItemDropped (main.ts:153)
    at dropCanvasHandler (canvas-ready-hook.ts:20)

**Comment by VeilOfOblivion** [comment]
Feeling bad opening 3 bugs in a row. But the module is great and I would love to use it in my PF2E campaign :)

**Comment by kamcknig** [comment]
This will be fixed in version 0.13.8!
