### ISSUE TITLE
Feature Request: Create a "merchant" type as a third option

### ISSUE THREAD

**Issue by VeilOfOblivion** [kamcknig/pick-up-stix#171]
This time, not a bug but a feature request :) 

It would be great to have a kind of fancier version of your containers that allows players to use it as a merchant. So the GM could stock them with items (like you do with the regular containers) and sets prices for those items. The players could then buy these things. For future developments, you could even add a selling option with e.g. a fixed % of the base price. Maybe even haggling could be implemented at some stage (making a check against a set DC).

I know there is the "Loot Sheet" module available. But as I am not into 5E but PF2E, this is not a great alternative for me. First of all, the PF2E version is not really working well yet (and it seems that the dev doesn't have time to really support both versions) and second, you already have such a great foundation with what your module can do already. Would be great to have even more options. The less amount of modules to use, the better (in my opinion).

**Comment by kamcknig** [comment]
Hey, keep them coming. I appreciate the thoughts. 

As for the bugs, I'll definitely get to them at some point, but I'm slowing down with the holidays and so not working on it as much as I would like right now.

As for this particular feature, it's actually in my backlog, and a second member of the community is working on something along these lines. I don't know all the features that we plan to put in it, but it is in the works

**Comment by VeilOfOblivion** [comment]
Sounds good to me. I can live with the bugs I reported as they are not breaking anything really and there are always workarounds. Would just be nice to use it in the way they suppose to work at some stage :) 

So... don't worry too much about them and enjoy this time of the year where everything slows down a bit. Even in those crazy times we are living in.

Keep up the great work!!
