### ISSUE TITLE
Pathfinder 1, unable to have unique inventory for mooks

### ISSUE THREAD

**Issue by ArdonDaros** [kamcknig/pick-up-stix#173]
In Pathfinder 1, it seems that items in inventory are always tied to original character and shared even across non-linked copies of it ("mooks").

**Steps to reproduce**
- Start new World using Pathfinder 1 system (and activate Pick-up-Stix module)
- Create an NPC actor (using sheet PF 1.ActorSheetPFNPC)
- Give the NPC actor any inventory item from the compendium
- Spawn multiple copies of the NPC actor on scene
- Open the inventory of any of the tokens on the scene (the NPC sheet title should display [token] prefix before the name of the npc)
- Drop any item from the inventory on the scene and close the character sheet
- Open the inventory of any of the other tokens on the scene and observe the item gone from their inventory as well. If no change is evident use F5 to refresh the view.
- Open the inventory of the original character in the Actors Directory and observe the item is gone.

- What this means: npc mooks cannot have unique inventories for lootable goods, as looting/dropping an item from one isolated copy removes the item from other copies. Do note the link actor data is unchecked.

**Comment by Rencos1** [comment]
There is a workaround for this problem. I am not sure if it will cause some side issues, but it works well for me. In Main.js in the function createLootToken just put in comment if (game.user.isGM) . It prevents the item to be created after it is deleted from the actor sheet when a player character drop an item.
**//if (game.user.isGM) {**
        if (typeof itemData === 'object') {
            itemData = await createItem({
                ...itemData,
                permission: {
                    default: 2
                },
                folder: game.settings.get('pick-up-stix', SettingKeys.tokenFolderId),
            });
        }
        if (typeof tokenData === 'object') {
            tokenData = await createToken({
                ...tokenData,
                flags: {
                    'pick-up-stix': {
                        'pick-up-stix': {
                            itemId: itemData
                        }
                    }
                }
            });
        }
    **//}**

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
