### ISSUE TITLE
Since the latest update, containers no longer function

### ISSUE THREAD

**Issue by SpironoZeppeli** [kamcknig/pick-up-stix#174]
**Describe the bug**
When clicking a container, nothing happens. Functionality is broken.

**To Reproduce**
1. Create a container
2. Click on container
3. See that nothing happens

**Expected behavior**
A container opens displaying items within

**Foundry Version**
0.7.8

**Pick-Up-Stix Version**
0.13.6

**Comment by kamcknig** [comment]
Thanks! Merged and released
