### ISSUE TITLE
System: 3.5e SRD, currency not deducted from containers.

### ISSUE THREAD

**Issue by SabbothO** [kamcknig/pick-up-stix#176]
**Describe the bug**
Players can pick up currency in container multiple times for infinite money.

**To Reproduce**
1. Add currency to container and have player loot it
2. Currency does not deduct from container

**Expected behavior**
Once looted, the currency should drop to zero and prevent multiple lootings.

**Screenshots**
N/A

**Foundry Version**
7.8

**Pick-Up-Stix Version**
13.8

**Comment by kamcknig** [comment]
Hi, thank you, this is a known issue and I believe the creator of the 3.5 system is working on this @Rughalt

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
