### ISSUE TITLE
Invisivility for players not working

### ISSUE THREAD

**Issue by 9ryex5** [kamcknig/pick-up-stix#178]
When I toggle visibility as GM, my players are still able to see loot.

![image](https://user-images.githubusercontent.com/43207603/102001748-5d969f00-3ced-11eb-9d37-1cf1eda755e2.png)
I placed a loot token next to an actor and set both invisible. Left side is GM view, right side is player view.

Foundry 0.7.8
Pick-Up-Stix 0.13.8

**Comment by kamcknig** [comment]
Hi, @9ryex5, someone else also had this issue, there might be a bug.


If you are using the D&D5E system, a workaround exists.

There is a module setting named "Loot Token Reveal" (only displayed for D&D5E right now). Please enable this setting, and optionally set a default reveal value in the setting as well. Any new token created will use this default value, any tokens already created will need to be edited manually. You can do so by opening the token HUD menu and there should be an input that you can use to set the minimum passive perception needed to reveal the token. If you set it high enough, this should prevent the players from seeing it.

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
