### ISSUE TITLE
Dropping and picking up a stacked item picks up the items separated instead

### ISSUE THREAD

**Issue by Krigsmaskine** [kamcknig/pick-up-stix#179]
**Describe the bug**
Thanks for checking into the other similar issue I reported so quickly! Perhaps I am just jumping the gun, apologies if so, but I was testing the current version 0.13.5 and tested again. It seems dropping an item with quantity, then picking said item(s) up again, will pick up separated copies of the item of the quantity, instead of a stack of the same quantity.

**To Reproduce**
1. Add an item with quantity, tested personally with javelins and torches.
2. Give the item a quantity higher than 1.
3. Drag and drop the item out of the inventory.
4. Pick up the item again with an actor.
5. The chat will correctly say "Picked up item (x9)", but the inventory is filled with separate items, instead of a single item with the expected quantity.

**Expected behavior**
If the item dropped was in a stack of quantity x before being dropped, the item picked up should also be in a stack of quantity x, instead of being picked up as x amount of individual items. 

**Screenshots**

**Foundry Version**
0.7.8

**Pick-Up-Stix Version**
0.13.5

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
