### ISSUE TITLE
Containers Not Working When Resized

### ISSUE THREAD

**Issue by EnragedLlama** [kamcknig/pick-up-stix#181]
Foundry: 0.7.9
Pathfinder 2nd Edition: 1.10.23.2638
Pick up Stix: 0.13.8

Reproduction: If i place any item down and set it to create Container, it will allow me to fill the container perfectly fine. But if I adjust the container size what so ever, bigger or smaller. The container breaks and no longer holds items and shows as a blank sheet.

Step 1: Drag-N-Drop potion or any item to map
Step 2: Select Container
Step 3: Adjust size to anything other than 1 and 1.
Step 4: Close container
Step 5: Select container again
Step 6: See that its a blank item sheet, without the item you drag and dropped.

This seems to be really finicky, i was able to get 1 out of about 50 or so attempts to actually hold the resize and maintain the item.
PS; I really love your module, I hope you can get it up and running for PF2E again.

**Comment by DariusWolfe** [comment]
Can confirm this issue. Also, changing the sprite to anything else seems to cause the same issue.

**Comment by EnragedLlama** [comment]
> Can confirm this issue. Also, changing the sprite to anything else seems to cause the same issue.

Changing the Sprite,
Changing the Width/Height,
Using the "Can Close" box.

Issue is persistant with a Clean PF2E world, and D&D 5E World.

Issue also occured without even changing anything. Dragging the token across, putting items in then Closing the box, Then reopening broke it in PF2E and in a clean 5E world.

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
