### ISSUE TITLE
Container not being recognised after any alteration until browser refreshed

### ISSUE THREAD

**Issue by Eldintux** [kamcknig/pick-up-stix#183]
**Describe the bug**
Can create a container without any problems. Can open it & see what's inside. I can close it again & when I open it it's still fine. But if I alter it in any way: change name, change Icons, add items or take item out, change it's size. Then the card it opens reverts back to the a normal item card claiming to be a weapon. I can get back the container by refreshing my web browser. Same fault happens in the stand alone virtual table top, but obviously you can't refresh that.

This happens in all systems I have tried (D&D 3.5 SRD -D35E, Simple World Building - worldbuilding & Ars Magica 5th Ed - arm 5e.

**Expected behavior**
The container should be able to be altered - put stuff in, take it out, rename, resize etc and be able to be opened again after closing.

**Screenshots**
![screen](https://user-images.githubusercontent.com/75202428/103181619-fce59580-489a-11eb-841a-eb2b2cc0c2cc.png)

**Foundry Version**
Foundry 0.7.9

**Pick-Up-Stix Version**
Pick-Up-Stix module 0.13.8

**Comment by AeroKinomoto** [comment]
I'm having the same issue.  With that said, you CAN refresh the FoundryVTT application by pressing F5, which fixes the issue in the same way as the browser (until you modify it again anyways).

**Comment by Hawttu** [comment]
Same issue here.

Foundry: 0.7.9
DnD5e: 1.1.1
Pick-Up-Stix: 0.13.8

**Comment by CampDungeon** [comment]
Noted this also.  As shown in the screenshot from Eldintux,  The Container always turns into a Weapon item.  The weapon item type is the default item type when creating a new item.  Perhaps a connection there.     Also,  the Item/should be container listed in the Item folder of PuS appears to be a weapon when viewed, but when dragged to the scene it (until changed) looks and acts like a container.  Refresh corrects that too.   Current version logging on Via Forge.    (D&D 3.5 SRD -D35E,

**Comment by SalieriC** [comment]
Same in SWADE 0.16.1

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
