### ISSUE TITLE
Players not able to drop items

### ISSUE THREAD

**Issue by weihanderz** [kamcknig/pick-up-stix#184]
**Describe the bug**
Items dropped to the ground by players are simply deleted.

**To Reproduce**
1. Log in as player
2. Drop an item on the ground

**Expected behavior**
Item should appear on the ground

**Foundry Version**
0.7.9

**Pick-Up-Stix Version**
0.13.8

**Comment by ToothlessTheNightFury** [comment]
I can reproduce this as well. I attempted the following to fix this:
1. Disable all modules except TidyUI and Pick Up Stix.
2. Give players all permissions.

I was still unable to drop an item as a player from my inventory. Dropping an item from a player's inventory as a DM, works, however.

**Comment by weihanderz** [comment]
Also true for when pick up stix is the only module.

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
