### ISSUE TITLE
Feature Request: Carryable Containers (i.e. Backpacks)

### ISSUE THREAD

**Issue by SalieriC** [kamcknig/pick-up-stix#185]
Container items that can be carried on the character sheet (i.e. Backpacks) would be a great addition for every system which does not have native support for these. The Backpack should have the weight of all items in it and it should be possible to open in and put items in and out without the need of a selected Token. It should also be possible to drop it to quickly remove the weight and pick up at a later time. when dropped to the canvas it should function similar to regular containers.

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
