### ISSUE TITLE
containers only work once when item is removed

### ISSUE THREAD

**Issue by vvatchdog** [kamcknig/pick-up-stix#187]
containers no longer function once something is taken out of them
players nor dm can open a container once something has been taken out of them, ex. i put a sword and shield in a chest, when the sword or shield is taken and the container is closed, when attempting to re-open the chest and take the other item, the chest/container is instead switched to be an 'item' page and not the container page, regardless of how i created the container

- create container using 'create item'
-  place objects in container
- take one or all objects out of the container
- when attempting to reopen container, instead of the container panel you're met with what appears to be an item sheet that is editable rather than the container interface.

this is with foundry 0.7.9 and the latest version of pick up stix.

**Comment by kamcknig** [comment]
@vvatchdog 

Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
