### ISSUE TITLE
GM can't access multiple Items in Container

### ISSUE THREAD

**Issue by pesky-wobbit** [kamcknig/pick-up-stix#189]
**Describe the bug**
Cannot open containers with more than one item.

**To Reproduce**
1. Drag an item onto the scene and choose container. (Works - can close, reopen and interact with container.)
2. Drag another item onto the container. (Works - new item accepted.)
3. Close the container.
4. Double click on the container to open. It doesn't look like the loot sheet and the items are inaccessible. (see screenshot)

**Expected behavior**
GM should be able to view or modify containers with more than one item.

**Screenshots**
![image](https://user-images.githubusercontent.com/477446/111539549-61025200-8744-11eb-95d5-6fd62be480dc.png)

**Foundry Version**
0.7.9

**Pick-Up-Stix Version**
0.13.8

Note: I have had multiple-item containers work for players, but usually it's broken in the same way.

**Comment by pesky-wobbit** [comment]
If I reload Foundry, I can interact with multi-item chests. If I modify the chest at all - add, pick up, or delete items, or change quantities - I have to reload.

**Comment by McShaker** [comment]
I also have this issue.

**Comment by kamcknig** [comment]
Sorry, but I am no longer maintaining this at this time. It might be something I come back to but for now, it's not being actively developed
