### ISSUE TITLE
does not work anymore since 0.8.6

### ISSUE THREAD

**Issue by warteckel** [kamcknig/pick-up-stix#193]
Since 0.8.6:
* Making an item does not allow anymore to see/modify the "trap" stats that are linked top the object
* Looking at an object previously cretaed in V 0.7.X it stills shows if there is a trap, a lock, etc... so datas are still here but the sheet does not show them any more
* 
![image](https://user-images.githubusercontent.com/84182699/121403094-de5fec00-c95a-11eb-999e-78825bf2afb6.png)
![image](https://user-images.githubusercontent.com/84182699/121403129-e881ea80-c95a-11eb-9eec-d14e66b46802.png)

**Comment by kamcknig** [comment]
Unfortunately, I no longer maintain this module and haven't in a while :/
