### ISSUE TITLE
Container Bug - cannot open

### ISSUE THREAD

**Issue by DMellswere** [kamcknig/pick-up-stix#194]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Foundry Version**
8.6

**Pick-Up-Stix Version**
0.13.8

Using the PF1e system, I cannot open containers while this module is active. Neither old nor newly made containers.

I have not tested other systems to see if this is cross game system.

**Comment by kyle-mcknight** [comment]
Hi, I'm sorry, but unfortunately I'm no longer maintaining this module :/

**Comment by DMellswere** [comment]
Oh quite alright. I should have checked that before putting q bug report in on a defunct module. -_- thanks anyways.
