### ISSUE TITLE
Items Cannot Be Picked Up if non-default Scale/Rotation

### ISSUE THREAD

**Issue by VoltCruelerz** [kamcknig/pick-up-stix#39]
If an item on the map is a non-default size or rotation, it cannot be picked up.

**Comment by kamcknig** [comment]
Never tested that! Are you setting the size of the token via the token configs image tab?

**Comment by VoltCruelerz** [comment]
Yep

**Comment by kamcknig** [comment]
Great! Thanks! For now I'll close this issue then.
