### ISSUE TITLE
Scale Non-Square Items

### ISSUE THREAD

**Issue by VoltCruelerz** [kamcknig/pick-up-stix#47]
If you have non-square images display as options in a container, they end up taking up extra space for their entire row.

![image](https://user-images.githubusercontent.com/4068550/88801143-3e9cd380-d177-11ea-81da-1b642df5c59e.png)

**Comment by kamcknig** [comment]
Thanks! I'll look into this. I hate html and css :-D

**Comment by kamcknig** [comment]
This will be fixed in the next release
