### ISSUE TITLE
Can no longer drag items to map

### ISSUE THREAD

**Issue by Sebbor117** [kamcknig/pick-up-stix#51]
Dragging items to the map stopped working after the latest update. 

Tested both with lootsheet5eNPC enabled and disabled. Did not work with or without. 

Worked yesterday before update without any problems.

**Comment by kamcknig** [comment]
Hi, another use has reported issues with Forien's Quest Log, Token Animation Tools and Token Hotbar. With any of those three add-ons installed, he is unable to drop items onto the map. If you have those installed, could you try disabling them and see if it works? If not, could you be sure to disable all mods besides this one and see if it works? If you can find a mod that is interfering I will add it to the list to check issues with.

**Comment by Sebbor117** [comment]
I have non of those modules installed. It works in my test world with just pick up strix enabled so its one of the others modules I have installed. 

I'll go through my list and see if I can find which one!

**Comment by Sebbor117** [comment]
So I now tested with all the modules I'm using and if I pair them one by one with pick up strix they all work. But as I add more and more I some times have to reload application any number of times before it might work. 

This seams to be either a load order problem or just that I'm using way to many modules at the same time.
I get it working with a majority of them, here's a list:
5e Encounter Builder
About Face
Actually Private Rolls
Ambient Doors
Animated Spell Effects
Background Volume
Better Ambient Loop
Calendar/Weather
Char Autoloader
Chat Images
Chat Message Accessibility Indicators
Chat Scrolling
Combat Enhancements
Combat Ready!
Combat Tracker Effect Icon Tooltips
Combat Utility Belt
Compendium Browser
Compendium Folders
Compendium Hider
Cozy Player
Crash's 5e Downtime Tracker
Cursor Hider
Darker Vision for 5e
D&D Audio Bundle - Hammer Home
Deselection
Dice So Nice!
Dice Tray
Display Mode
Easy Target
Expander
Follow Me!
Forgotten Adventures Extensive DM Screen
FXMaster
Game Audio Bundle 1
Game Audio Bundle 2
Game Audio Bundle 3
Game Audio Bundle 4
Grid Scale Menu
Health Estimate
Hidden Initiative
Image Previewer
Item Containers
Item Delete Check
Jinker's Animated Art Pack
Layer Hotkeys
Lazy Money
Loot Sheet NPC 5e
Maestro
Magic Items
Mess - Moerills enhancing super-suit(e)
Michael Ghelfi Audio Pack
Minor Quality of Life Improvements
Mount Up!
Multilevel Tokens
Music d20 Sampler
No Token Animations
Ostenwold Starter Town by Tom Carton
Pick-Up-Strix
Playlist Importer
Point of Vision
PopOut!
QuickSceneView
Rount-Finder
Sane Magic Item Prices Compendium
Shared Data (My compendiums)
Show Drag Distance
Simple Name Generator
Sky's Alternate 5th Edition Dungeon & Dragons Sheet
Spellarena Battlemap Collection
Tabbed Chatlog
The Furnace
Tidy UI - Game Settings
Tidy5e Sheet
Tiles Browser
Token Action HUD
Toke Mold
Token Tooltip
Token Vision Tweaks
Tourch
Travel Pace for D&D 5e
Turn Alert
Turn Marker
Vance's Sidebar Resizer
Virtual Tabletop Assets - D&D Beyond Integration
Virtual Tabletop Assets - Iconizer
Virtual Tabletop Assets - Party overview
Virtual Tabletop Assets - Tokenizer
Whisper Box

-----

These all work, but not a single one of them work at the same time as the big list.
Dynamic effects
Popout Resizer
Token Hotbar
Trigger Happy

Hope this helps in anyway and let me know if I can help with anything else.

**Comment by kamcknig** [comment]
Thanks for the info. I'm not going to lie, because of the vagueness and difficulty in finding which is causing the issue, this might remain semi-low priority. I do however, use some of these in my own game, so I'll attempt to rule out some of those. There are probably others that we can rule out that don't have anything to do with tokens.

**Comment by Sebbor117** [comment]
Yeah understandable. If you need more testing done let me know I'll gladly help if/ when I have the time.

**Comment by kamcknig** [comment]
Appreciate it! I did just release 0.4.3. I found a compatibility issue with Foundry 0.6.5 and fixed it. So if you are on that version of Foundry, please update and try again!

**Comment by Sebbor117** [comment]
Maybe that was the problem. Now it works as it should with my regular world!

**Comment by kamcknig** [comment]
That's great! Glad to hear
