### ISSUE TITLE
Feature Request - Add tooltip for item description

### ISSUE THREAD

**Issue by Khybersghost** [kamcknig/pick-up-stix#53]
Possible to get tooltip info for items already placed on the canvas so you can get a description of the item before picking it up?

**Comment by kamcknig** [comment]
Hi, would you like the actual item description as defined in the item data? What if it is a container? Do you want the description of the container?

**Comment by Khybersghost** [comment]
A description as defined by the item data would be great. If it's possible to set a custom description for the item, even better, but that seems like a lot more work.

**Comment by kamcknig** [comment]
You should be able to edit the Item description yourself and therefore give it a custom description, but when I implement this I'll allow for an optional "description override" to use for the tooltip
