### ISSUE TITLE
Button Stretched

### ISSUE THREAD

**Issue by VoltCruelerz** [kamcknig/pick-up-stix#62]
**Describe the bug**
The container button is vertically stretched for large tokens.

**To Reproduce**
1. Place an actor with a size larger than medium on the map.

**Expected behavior**
The button would be a normal size.

**Screenshots**
![image](https://user-images.githubusercontent.com/4068550/89080514-14097100-d357-11ea-99e6-406db6e7fa21.png)

![image](https://user-images.githubusercontent.com/4068550/89080429-d0166c00-d356-11ea-8de1-b5d476ac099b.png)

**Foundry Version**
0.6.5

**Pick-Up-Stix Version**
0.5.0

**Comment by kamcknig** [comment]
I have re-done the GUI completely in 0.7.2 of the module and those icons are no longer there!
