### ISSUE TITLE
Drag Upload Incompatibility

### ISSUE THREAD

**Issue by Alexis-Grimm** [kamcknig/pick-up-stix#64]
I'm using foundry 0.6.5, Dnd5e 0.94, Drag Upload 1.2.1, and Pick-Up-Stix version 0.6.0. I cannot seem to place items while drag upload is active, thought drag upload is also really useful.  (I have a bunch of other modules as well but that seems to be the only one causing problems) I don't have Forien's Quest Log, Token Hotbar, or Token Animation Tools. Thanks for the great module!

**Comment by Avitale34** [comment]
Same issue here, great module would love to make these two compatible!

**Comment by kamcknig** [comment]
I haven't used that module, I'll install and test compatibility.

**Comment by WildBillLives** [comment]
I can confirm this issue,  I recently added "Drag Upload v1.21" to my active modules, and unfortunately now pick-up-stix does not do anything.

**Comment by kamcknig** [comment]
Unfortunately I think I found today that our two modules just wont' ever work together in foundry 0.6.5. Because of the way we are both handling the drag/drop, foundry doesn't do well with it. In 0.7.0 it might get better as I'm not using the same method to handle it with new API features.

**Comment by kamcknig** [comment]
@WildBillLives please try version 0.7.10. I have updated it with a possible compatibility fix.

**Comment by BradKriss** [comment]
I just tried it and it looks like they're playing nice together for me now! Nice fix!

**My Environment:** 
Foundry: 6.5 (forge hosted)
D&D: 0.95
DragUpload: 1.2.1
Pick-up-stix: 0.7.10

**Comment by WildBillLives** [comment]
> 
> 
> @WildBillLives @Alexis-Grimm, @Avitale34 please try version 0.7.10. I have updated it with a possible compatibility fix.

Yes, very good - no issues from my initial testing of both modules together - thank you very much!
