### ISSUE TITLE
Updated Manifest

### ISSUE THREAD

**Issue by Alexis-Grimm** [kamcknig/pick-up-stix#71]
I noticed that there has been two releases since 0.6.0 of Pick up stix, is it intentional that this isn't available through the foundry module installer?

**Comment by kamcknig** [comment]
Hi, yes it was. I had created releases for myself that I was testing, but they were still in the github project. But they were not meant for live use. The current version 0.7.2 is the most recent "live" version that contains my intial re-write of the GUI
