### ISSUE TITLE
Feature Request - Resize Generated Icons

### ISSUE THREAD

**Issue by shinkei13** [kamcknig/pick-up-stix#87]
It would be amazing if you could customize the size of the tokens created on drop. As they are now, players can sometimes mistake dropped items for NPC icons. I've even had an instance where a player lost their token underneath an item. Ideally, we could choose a width and height similar to the controls we have for tokens.

**Comment by kamcknig** [comment]
In my previous incarnation you still had the ability to use the normal token config rather than my item config. When switching to the new GUI, that ability was lost. However, I agree the size should be configurable. I do plan on adding that back in for sure

**Comment by kamcknig** [comment]
There is now a scale input on the item config page that allows you to change the scale from .1 to 2. This is available in 0.7.13
