### ISSUE TITLE
Feature Suggestion: Premade containers

### ISSUE THREAD

**Issue by Alexis-Grimm** [kamcknig/pick-up-stix#88]
Something that would be exceptionally useful would be the ability to create containers in the items directory with specific open and closed images so that you can keep a nice library of various different containers based on your purposes, so you don't have to spend any time switching from the default images. Another part of this that would be useful would be the ability to have a premade container use a roll-table to determine its inventory when placed down but that's just an extra thing honestly. Would be very useful when improvising an encounter or when using it to create lootable bodies and such. Another little suggestion within this would be the ability to configure default appearances for specific items when placed on the ground, instead of just using the item icon, but once again, that's just a little extra detail. This is such a great module thank you so much.

**Comment by kamcknig** [comment]
100% will be adding support for roll tables, it is on my list. It's hard to decide what to work on next! 

I also agree on the other points. Thank you for the suggestions and they'll be added to the list.

**Comment by kamcknig** [comment]
@Alexis-Grimm Version 0.8.0 you can use the 'create item' button on the item's directory and use the type selector to choose 'container' and create a container item directly. It's quite untested. But it's an initial pass
