### ISSUE TITLE
Not Hidden

### ISSUE THREAD

**Issue by rinnocenti** [kamcknig/pick-up-stix#91]
**Describe the bug**
It now appears that the item on the map is no longer a token. It is not possible to access the description texts, or even make it hidden.

Foundry 0.6.5

**Pick-Up-Stix Version**
0.7.13

**Comment by kamcknig** [comment]
@rinnocenti You can now make a loot token invisible in the latest version. The controls have changed, right clicking will bring up a HUD menu to allow changing locked/visibility state and open the config. You can also open the config via double clicking or double right-clicking
