### ISSUE TITLE
Minor Feature Request - Add the possibility in the case of the same consumable objects to merge them by doubling weight and price when picked up

### ISSUE THREAD

**Issue by p4535992** [kamcknig/pick-up-stix#93]
**Describe the feature**

When pick up 5 potion of the same type it will be nice to have them already merged in one item on the characters sheet.
So my request is to add the possibility in the case of the same objects to merge them by doubling weight and price  when picked up,

**To Reproduce**

1. Put for example five red potion on the scene
2. Go to pick up the potions
3. Go to the inventory instead five red potion, i want to see one red potion with quantity set to 5.

This is  a very minor request, and it's have a very low priority.

**Foundry Version**

Foundry VTT Version: 0.7.1
Operating System: \[Linux\]
How Are You Using Foundry: \[Linux,Native Application (Electron), Chrome\]
Which Game System: Dungeons and Dragons 5th Edition, version 0.95
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Pick-Up-Stix Version**

0.8.0

**Comment by kamcknig** [comment]
Hi, I apologize, but I will no longer be maintaining this. To support multiple systems was taking too much time. I have offered to let anyone take it over on the discord, but so far no one has.
