### ISSUE TITLE
Getting Errors in console on item drop on map

### ISSUE THREAD

**Issue by Freelancerjw** [kamcknig/pick-up-stix#97]
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/pick-up-stix.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/hooks.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/settings.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/target-enhancements/src/pixi-filters.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/item-config-application.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/main.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/models.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/overrides.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/preloadTemplates.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/utils.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/container-image-selection-application.js.map
> DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/choose-token-application.js.map

Was excited to see and try this module, but I couldn't seem to get it to work. Upon opening the console, this is the error I found upon trying to drag and drop items onto the map. Foundry VTT 0.6.6, Starfinder 0.4.10. I also couldn't get it to work with the 5e 0.96 system either.

**Comment by kamcknig** [comment]
Interesting. Those errors should be benign as that's just trying to locate the JS to TS mapping files. I actually have that fixed in 0.8.5 though I still need to change it as I think the map files are now being shipped with the live code. Oops.

As for it not working, especially in 5E that's very strange. Have you tried disabling all other modules? If so, and it still doesn't work then please feel free to PM me on the Foundry Discord and I'll be happy to help out. There were some definite compatibility issues with other modules that relied on dragging/dropping functionality, though I have since fixed/hacked a lot of those.

**Comment by altair984** [comment]
im working with Foundry VTT 0.6.6 and 5e 0.96 system. I have the same error. The item dont drag and drop into the map.

DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/pick-up-stix.js.map
DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/hooks.js.map
DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/settings.js.map

**Comment by altair984** [comment]
hi, i install the last version update. i did it and im working with Foundry VTT 0.6.6 and 5e 0.96 system. I have the same error. The item dont drag and drop into the map.

that is fixed:
Now the console dont show that: 
DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/pick-up-stix.js.map
DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/hooks.js.map
DevTools failed to parse SourceMap: http://localhost:30000/modules/maps/module/pick-up-stix/settings.js.map

**Comment by kamcknig** [comment]
Hi there!

So Someone else just had the issue and what I didn't realize is my version check would make it not work when it was above version 0.6.5.

I just updated about 5 minutes ago to Pick-Up-Stix 0.8.8. please try that version. It should work with Foundry 0.6.6

**Comment by Freelancerjw** [comment]
I updated to Foundry 0.7.1 last night to try and it worked fine, downgraded back to 0.6.6 after seeing your latest message and it works now even with Drag Upload enabled! Thanks! Excited to try it out in a session :)

Now if only the currency portion of the containers could be configured to work with Starfinder :P Ultra minor and totally a QoL thing, but I wouldn't complain! Thanks again!
