### ISSUE TITLE
Feature Request: Keys for Chests

### ISSUE THREAD

**Issue by Torgaard** [kamcknig/pick-up-stix#98]
First: Thank you so much for you work - what a fantastic add-on!

Feature Request: I just thought a neat feature might be if a chest could only be opened if an Actor had a specific key (Loot item) in their inventory. Maybe an addition to your options interface for items after dropping them on a Scene (that = type 'Container'?) , where you'd now also have a checkbox of "Requires key" and a field to enter the name of the key (ie 'Orc Chieftain's Key'). Then maybe you can code Pick-up Stix to simply check to see if an Actor attempting to open the chest has that specifically named key (Loot item) in their inventory?

**Comment by kamcknig** [comment]
I like it. I'll add it to my trello board! Thanks for using it and thanks for the compliment!

**Comment by kamcknig** [comment]
Closed as it's on my trello
