### ISSUE TITLE
Money never sets the value to 0 for players in the container

### ISSUE THREAD

**Issue by LucianoMonsores** [kamcknig/pick-up-stix#99]
When a player picks money (platinum, gold, silver...) using the hand icon, it does not reset (set the value to 0) and also allows players to pick the amount several times. When I try to do it as a DM, the amounts of money are set to 0. Could you please check that?

Thanks, 
Luciano

**Comment by kamcknig** [comment]
Hmm, interesting, thanks for reporting it.

I did just confirm that happens for me too! Thanks for reporting it.

**Comment by LucianoMonsores** [comment]
No problem and thanks for taking a look.
This module is very good and once fixed, I will add this functionality to my game.

**Comment by kamcknig** [comment]
Hi, this should now be fixed in version 0.8.9
